pycuda/gpuarray.py, test/test_gpuarray.py
This adds the option to use "-1" as an "unknown dimension" when reshaping gpuarrays (as requested in #62), so that e.g.
a_gpu.reshape(32, -1)
does the right thing.
=> Add support for unknown dimension in reshape

src/wrapper/wrap_cudadrv.cpp
I've done some basic tests on the memset async and they seem to work functionally, although they don't seem improve speed much vs. the synchronous version.
More importantly, I was wondering whether there was a specific reason that the memcpy_peer_async was commented out?
=> Add async memset methods to driver, uncomment peer async copy method

examples/demo.py, examples/demo_struct.py, examples/download-examples-from-wiki.py, examples/dump_properties.py, examples/fill_gpu_with_nans.py, examples/hello_gpu.py
Port the examples to python3 for those that have switched to the newer version of the interpreter.
=> Port examples to Python 3.

pycuda/compiler.py
=> add option to compile device-independent PTX files with pycuda.compiler.compile()

pycuda/compiler.py
Fatbin embeds prebuilt for set of specified real architectures cubin's
and PTX assemblies for set of specified virtual architectures, allowing
driver to load prebuilt cubin if there is any for current real GPU, or
to assemble PTX from closest virtual GPU architecture.
This can be used for distributing CUDA-powered applications without need
to install NVidia CUDA Toolkit (nvcc) and development environment on
target platform.
.cu files can be precompiled to fatbin's on build server with
fatbin = pycuda.compiler.compile(
cu_file_text,
options=[
"-gencode", "arch=compute_20,code=compute_20",  # build PTX for compute_20 virtual GPU architecture
"-gencode", "arch=compute_20,code=sm_20",       # build cubin for sm_20 real GPU architecture
"-gencode", "arch=compute_30,code=compute_30", …
=> add option to compile nvcc's fatbin

pycuda/gpuarray.py
Previously, the following would cause an error:
>>> a = pycuda.gpuarray.to_gpu(numpy.arange(16).reshape((4,4)))
>>> b = a[::3]
>>> b.shape
(2, 4)
>>> b[1]
array([12, 13, 14, 15])
=> slice size should round up, not down

pycuda/gpuarray.py
This PR fixes two small bugs in  `gpuarray.set_async` that were introduced back in #76.
=> Fix gpuarray.set

src/wrapper/wrap_cudadrv.cpp, test/test_driver.py
Replaced PyArray_SIZE(ary) with PyArray_NBYTES(ary).
pycuda.driver.register_host_memory() was passing
the size of the array in elements, rather than
the length of the array in bytes when
creating a register_host_memory class.
This resulted in "Invalid Argument" errors
when calling asynchronous memory copies on
the entire array.
This solves the issues in #46.
=> register_host_memory corrected to pin the array length in bytes, rather than elements

pycuda/gpuarray.py
Within `gpuarray.set_async`, the `stream` keyword
argument in the call to `gpuarray.set` was
always set to `None`.
``` python
return self.set(ary, async=True, stream=None)
```
This keyword argument is now always set to value
supplied in the arguments to `gpuarray.set_async`.
```python
return self.set(ary, async=True, stream=stream)
```
Within `_memcpy_discontig`, `Memcpy2D.__call__`
was being called for asynchronous cases as follows:
```python
copy(stream=stream)
```
However, this does not match the C++ function
definition. Instead, they are now called as follows:
```python
copy(stream)
```
=> Fix stream parameters in asynchronous methods.

pycuda/gpuarray.py, test/test_gpuarray.py
Sometimes useful in cases where numpy and GPUArray shapes
don't match due to length 1 dimensions. This can occur
when slicing GPU and CPU arrays and helps to suppress warnings
about non-matching array shapes.
=> Add a GPUArray.squeeze() method.

pycuda/cuda/pycuda-complex.hpp
This PR adds return by reference versions of real() and imag() to allow setting of the real and imaginary parts of a complex number in a kernel.  Technically this is possible now by accessing ```_M_re``` and ```_M_im``` directly but that's bad practice.
=> Add ability to set real and imaginary components of complex numbers

pycuda/cuda/pycuda-helpers.hpp, pycuda/driver.py, test/test_driver.py
Extension for 2D and 3D; Textures and Surfaces with fp support. Added support for direct use of doubles, complex floats, complex doubles. Added a general function "np_to_array" to make CUDA Arrays of supported direct types and hacks for double, float complex and double complex. Finally a test for the added functions.
Will be nice to complete the work for long long integers, but it most use an ugly type cast passing from int2 -> double -> long long, and vice versa. And, for me is not clear if it can be correctly init data for arrays of this type.
Regards,
Roberto
=> extFPTextureSurfaces

doc/source/driver.rst, src/cpp/cuda.hpp, src/wrapper/wrap_cudadrv.cpp
I added the ability to cast  a pycuda.driver.Array handle pointer to an integer.  I've been using this to perform allocations using pycuda then pass them to previously compiled CUDA code.
Per your email, I've left these features undocumented.
=> Add ability to get handle to CUDA Arrays

src/cpp/cuda.hpp
Some fields were left uninitialized, which doesn't seem very Pythonic.
The CUDA_MEMCPY3D structure is now value-initialized, which ensures all
its members are zero.
=> Zero-initialize all fields of Memcpy*D

doc/source/driver.rst, pycuda/compiler.py
This enables kernel caching to be controlled at the environmental level.
This is useful as while it is possible to control the caching behaviour by passing `cache_dir` to `SourceModule` this is not always practical.  A good example of this is when one is using the auto-generated reduction kernels.  Here, there is no mechanism to control what values get passed down to `SourceModule`.  The result is an inconsistent caching behaviour for applications that combine their own kernels with those from other source.
=> Allow the caching behaviour to be controlled globally.

pycuda/cuda/pycuda-helpers.hpp, test/test_driver.py
When enabling Surface Textures as 2D Layered form the corresponding access from textures were no supported for all implemented types. With this extension Doubles and PyComplex are now supported for 2DLayered access.
=> Surf an dtex extensions

src/cpp/cuda.hpp
This corrects an issue in `DeviceAllocation.as_buffer` whereby the resulting views are read-only.
The issue stems from the combination of a confusing Python API (where read/write views are created by passing `PyBUF_WRITE`) and lax error checking on the part of this API.
=> Ensure the views from DeviceAllocation.as_buffer are writeable.

pycuda/compiler.py
Solves error generated by using sys.maxint constant in Python 3.1.5^, sys.maxsize is available for use in Python 2.0.0.
Python docs for reference:
- sys.maxint deprecated in Python 3.1.5^: https://docs.python.org/3.1/whatsnew/3.0.html#integers
- sys.maxsize supported in Python 2.6^ : https://docs.python.org/2.6/library/sys.html#sys.maxsize
=> Update  compiler.py

src/cpp/cuda.hpp, src/wrapper/wrap_cudadrv.cpp
I need access to the context handles to pass to another library, so I added the `handle` property similar to how it is done for the stream wrapper.
=> Add access to cuda context handle

doc/source/array.rst
Fixed a confusing typo in the docs, where the class name "GPUArrray" was spelled incorrectly.
=> GPUArrray --> GPUArray

src/wrapper/wrap_cudadrv.cpp
1.x targets were removed in 9.0
=> Fixing CUDA 9.0 build

pycuda/gpuarray.py
This small update should fix the shape of arrays indexed with negative strides (when it should be `N` it was `N+2`).  I think the strides and offset calculations are already correct though.
=> Fix slicing with negative stride.

pycuda/elementwise.py
Thank you for maintaining PyCUDA.
I'd like to use a texture reference in an ElementwiseKernel.
It was hard to find documentation on how to do that.
If I understand correctly, you need to define a texture reference (say, in the preamble) and then call get_texref on the module so you can bind it to an array. Is there another way to do this?
If not, please add get_texref to the ElementwiseKernel class.
I made an attempt. Don't know if this is right.
=> Add get_texref() to ElementwiseKernel

doc/source/driver.rst
The documentation incorrectly states that the method is called stop whereas the correct name is stop_profiler.
=> Fix documentation related to stop_profiler method.

src/cpp/cuda.hpp
Previously the same fix has been applied to pointer_holder_base.as_buffer but not for device_allocation class.
=> fix to make device_allocation.as_buffer() result writable

pycuda/curandom.py
Fixed DeprecationWarning:
> curandom.py:612: DeprecationWarning: This function is deprecated. Please call randint(0, 2147483646 + 1) instead
>   0, (1 << 31) - 2, generator_count),
(numpy.random.random_integers: Deprecated since version 1.11.0.)
=> replaced deprecated numpy.random.random_integers with randint

setup.py
Installing pycuda shouldn't bring in a test runtime, only
when you are planning to run the test suite of pycuda should
this be brought in.
=> Pytest is a test-requirement not a runtime requirement

pycuda/elementwise.py
Move extern "C" around the main ElementWise function to avoid linkage issues with preamble (e.g. when using cuda_fp16.h)
=> Move extern "C" around the main ElementWise function

doc/source/array.rst, pycuda/curandom.py, test/test_gpuarray.py
With this version, the input array can be used to supply the per-element lamba value. This is similar to what numpy.random.poisson() allows, either supplying a shape and one lambda value, or an array of lambda values.
This is very useful when simulating detector data for imaging, where each point has a different expected value.
Let me know if you want examples, there are currently none for the random-number generators.
=> Add in-place poisson random-number generation

doc/source/array.rst, pycuda/elementwise.py, pycuda/gpuarray.py, test/test_gpuarray.py
Similar to np.conj/conjugate function
Advantages:
- easy to do in-place conjugate, and
- write conjugate result to another GPUArray
- self.conjugate() is compatible with both python built-in number types (for example: `(1).conjugate()`, `(1+2j).conjugate()` ...) and numpy ndarray
=> add "out" parameter to GPUArray.conj(); add equivalent GPUArray.conjugate() method

pyproject.toml
Build against the oldest C_API_VERSION available for the current Python
version, to maximise compatibility of the resulting installation.
Closes #271.
=> Add a pyproject.toml to control build-time numpy version

doc/source/array.rst, doc/source/tutorial.rst, doc/source/util.rst, examples/cai_cupy_arrays.py, examples/cai_numba.py, pycuda/autoprimaryctx.py, pycuda/driver.py, pycuda/gpuarray.py, test/test_driver.py
This PR adds support for version 3 of the [CUDA Array Interface](https://numba.readthedocs.io/en/latest/cuda/cuda_array_interface.html):
- GPU Arrays export the interface so that they can be passed to other supporting libraries.
- Function calls check for the presence of the interface and use the data pointer from it if found, so other libraries' arrays can be passed to PyCUDA-compiled kernels.
Documentation, tests, and examples for the interface going in both directions are added.
=> Support the CUDA Array Interface

doc/source/index.rst
This PR is pretty simple -- it removes duplicate 'reikna' entry from the 'Other Software' list
=> doc/source/index.rst: remove duplicate reikna entry

aksetup_helper.py, examples/from-wiki/mandelbrot_interactive.py, pycuda/cuda/pycuda-helpers.hpp, test/test_gpuarray.py
There are small typos in:
- aksetup_helper.py
- examples/from-wiki/mandelbrot_interactive.py
- pycuda/cuda/pycuda-helpers.hpp
- test/test_gpuarray.py
Fixes:
- Should read `subtraction` rather than `substraction`.
- Should read `support` rather than `supprt`.
- Should read `right` rather than `rigth`.
- Should read `preferred` rather than `prefered`.
Closes #294
=> docs: fix a few simple typos

pycuda/driver.py
If pycuda has detected a CUDA runtime via nvcc.exe discovery, return to prevent a misleading warning, consistent with CUDA_PATH usage above.
=> Prevent warning on nvcc_path add

pyproject.toml
CI on gitlab: https://gitlab.tiker.net/inducer/pycuda/-/merge_requests/new?merge_request%5Bsource_branch%5D=oldest-numpy
=> use oldest-supported-numpy

pycuda/curandom.py, test/test_gpuarray.py
This MR allows random number generators to work with large (>=2**31 elements) arrays.
(note this is done regardless of whether it's a _sensible_ idea to generate 2**31 or 32 elements with rng which may have a smaller period, but often it may not matter).
The tests are rather long (testing all rng's and all possible types and functions, sizes 2**31 and 2**32 when possible).
This needs some sanity check:
*  I have only changed the `int` types when it seemed appropriate - for example in the `..skip` functions I've left the `skip` parameter with its original type.
* it may be necessary to cast types in expressions like `blockIdx.x*blockDim.x+threadIdx.x` since the underlying types are `uint32` ? I don't actually know what range of values will be taken by these variables.
Should fix #413
=> Add support for array sizes >=2**31 for random number generation

setup.py
Since the build-time Numpy version is already controlled by `build-system.requires` in `pyproject.toml`, it is not necessary to specify the Numpy version in `setup.py`. The latter would cause dependency resolution issues when PyCuda is installed using Poetry, see [this issue](https://github.com/python-poetry/poetry/issues/8830)
=> Remove setup_requires to avoid dependency resolution issues with Poetry

aksetup_helper.py, setup.py
* we have to set BOOST_USE_WINDOWS_H=1 because of this bug: http://stackoverflow.com/questions/18134148
* remove '/EHsc' and '/FORCE' when compiling with mingw instead of msvc
=> fix defaults for mingw builds

pycuda/gpuarray.py, test/test_gpuarray.py
Hi Andreas,
Somehow gpuarrays' `mul_add` did not use the supplied `stream` parameter. Similarly, the `allocator` parameter of `subset_sum` was not used either. 
This PR should fix that, and also adds an optional `out` parameter to `mul_add`.
=> Use stream in mul_add if given and allocator in subset_sum

doc/array.rst, doc/conf.py, doc/driver.rst, doc/gl.rst, doc/misc.rst, doc/util.rst, src/wrapper/_pvt_struct_v3.cpp, src/wrapper/wrap_cudadrv.cpp
for details, see https://github.com/python/cpython/issues/85275
I'm not sure what `CUDAPP_CALL_GUARDED` does or if we perhaps should catch errors there and call `PyBuffer_Release` if an error is thrown.
I also don't know if the failures here are meant to be fatal or not.
Only compile tested at this point.
=> Python 3.13 removed the old buffer interface

pycuda/compiler.py
When subprocess runs successfully, the stdout is bytes and is decoded later. However, it is set to a `str` literal when the subprocess fails. Change it to bytes literal to get decoded without problem.
=> Use bytes as output when nvcc version could not be determined
